void* MFXClose() { return 0; }
void* MFXInit() { return 0; }
void* MFXInitEx() { return 0; }
void* MFXJoinSession() { return 0; }
void* MFXQueryIMPL() { return 0; }
void* MFXQueryVersion() { return 0; }
void* MFXVideoCORE_GetHandle() { return 0; }
void* MFXVideoCORE_SetFrameAllocator() { return 0; }
void* MFXVideoCORE_SetHandle() { return 0; }
void* MFXVideoCORE_SyncOperation() { return 0; }
void* MFXVideoDECODE_Close() { return 0; }
void* MFXVideoDECODE_DecodeFrameAsync() { return 0; }
void* MFXVideoDECODE_DecodeHeader() { return 0; }
void* MFXVideoDECODE_Init() { return 0; }
void* MFXVideoDECODE_QueryIOSurf() { return 0; }
void* MFXVideoENCODE_Close() { return 0; }
void* MFXVideoENCODE_EncodeFrameAsync() { return 0; }
void* MFXVideoENCODE_GetVideoParam() { return 0; }
void* MFXVideoENCODE_Init() { return 0; }
void* MFXVideoENCODE_Query() { return 0; }
void* MFXVideoENCODE_QueryIOSurf() { return 0; }
void* MFXVideoENCODE_Reset() { return 0; }
void* MFXVideoUSER_Load() { return 0; }
void* MFXVideoVPP_Close() { return 0; }
void* MFXVideoVPP_Init() { return 0; }
void* MFXVideoVPP_RunFrameVPPAsync() { return 0; }
